# Generated by Django 4.2.2 on 2024-07-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comapny',
            new_name='Company',
        ),
    ]
